#  Computer Vision (CS-512) : Homework 0

 Benjamin Scialom   
 A20432063

## Exercise A  


In [1]:
import numpy as np

# Variables

vecA = np.array([1, 2, 3])
vecB = np.array([4, 5, 6])
vecC = np.array([-1, 1, 3])

A = np.matrix('1; 2; 3')
B = np.matrix('4; 5; 6')

Ex = np.array([[1], [0], [0]])
Ey = np.array([[0], [1], [0]])
Ez = np.array([[0], [0], [1]])

A_normalized = (1/np.linalg.norm(vecA))*vecA
B_normalized = (1/np.linalg.norm(vecB))*vecB
Ex_normalized = (1/np.linalg.norm(Ex))*Ex
Ey_normalized = (1/np.linalg.norm(Ey))*Ey
Ez_normalized = (1/np.linalg.norm(Ez))*Ez

# Answers

ResA_1 = 2 * A - B
print "\n A.1) \n 2A - B = ", ResA_1


ResA_2_a = np.linalg.norm(vecA)
print "\n A.2.a) \n ||A||=", ResA_2_a

Res_2_b = np.arccos(np.vdot(A_normalized, Ex_normalized)*(1/(np.linalg.norm(A_normalized)*np.linalg.norm(Ex_normalized))))
print "\n A.2.b) The angle A relative to the positive X axis is ", Res_2_b

ResA_3 = (1/np.linalg.norm(vecA))*vecA 
print "\n A.3) the unit vector in direction of A is : ", ResA_3
print
print "Notice: that's correspond to the vector A_normalized I used into the previous question."


ResA_4_a = np.vdot(A_normalized, Ex_normalized)*(1/(np.linalg.norm(A_normalized)*np.linalg.norm(Ex_normalized)))
ResA_4_b = np.vdot(A_normalized, Ey_normalized)*(1/(np.linalg.norm(A_normalized)*np.linalg.norm(Ey_normalized)))
ResA_4_c = np.vdot(A_normalized, Ez_normalized)*(1/(np.linalg.norm(A_normalized)*np.linalg.norm(Ez_normalized)))
print "\n A.4) The direction cosines of A are :\n"
print "Related to X axis : ", ResA_4_a
print "Related to Y axis : ", ResA_4_b
print "Related to Z axis : ", ResA_4_c

ResA_5_a = np.vdot(vecA, vecB)
ResA_5_b = np.vdot(vecB, vecA)
print "\n A.5.a) The scalar product between A and B : A.B =", ResA_5_a
print "\n A.5.b) The scalar product between B and A : A.B =", ResA_5_b
print 
print "Notice: The scalar product is commutative"

ResA_6 = np.arccos(np.vdot(A_normalized, B_normalized)*(1/(np.linalg.norm(A_normalized)*np.linalg.norm(B_normalized))))
print "\n A.6) The cosine between the vectors A and B is : ", ResA_6

print "\n A.7) I did not succeeded in doing this question on Python. The issue is that I don't know how to push the program to do a choice of vector."

ResA_8_a = np.cross(vecA,vecB)
ResA_8_b = np.cross(vecB, vecA)
print "\n A.8) The cross product between A and B is : A x B = ", ResA_8_a
print "\n A.8) The cross product between B and A is : B x A = ", ResA_8_b
print 
print "Notice: We can see that the cross product between A and B is the opposite to the cross product of B and A"

ResA_9 = np.cross(vecA, vecB, axis=0)
print "\n A.9) A vector which is perpendicular to A and B could be : ", ResA_9

print "\n A.10) I did not succeeded in doing this question in Python. Once again, I don't know how to push the program to make a choice."

ResA_11_a = np.transpose(A).dot(B)
ResA_11_b = A.dot(np.transpose(B))
print "\n A.11.a) Transposed of A(1x3) multiplies by B(3x1) is equal to :  ", ResA_11_a
print "\n A.11.a) Transposed of A(3x1) multiplies by B(1x3) is equal to :  \n", ResA_11_b




 A.1) 
 2A - B =  [[-2]
 [-1]
 [ 0]]

 A.2.a) 
 ||A||= 3.7416573867739413

 A.2.b) The angle A relative to the positive X axis is  1.3002465638163236

 A.3) the unit vector in direction of A is :  [0.26726124 0.53452248 0.80178373]

Notice: that's correspond to the vector A_normalized I used into the previous question.

 A.4) The direction cosines of A are :

Related to X axis :  0.2672612419124244
Related to Y axis :  0.5345224838248488
Related to Z axis :  0.8017837257372732

 A.5.a) The scalar product between A and B : A.B = 32

 A.5.b) The scalar product between B and A : A.B = 32

Notice: The scalar product is commutative

 A.6) The cosine between the vectors A and B is :  0.2257261285527332

 A.7) I did not succeeded in doing this question on Python. The issue is that I don't know how to push the program to do a choice of vector.

 A.8) The cross product between A and B is : A x B =  [-3  6 -3]

 A.8) The cross product between B and A is : B x A =  [ 3 -6  3]

Notice: We can see

## Exercise B

In [2]:
import numpy as np

# Variables

A = np.matrix('1 2 3; 4 -2 3; 0 5 -1')
B = np.matrix('1 2 1; 2 1 -4; 3 -2 1')
C = np.matrix('1 2 3; 4 5 6; -1 1 3')

# Answers

ResB_1 = 2 * A - B
print "\n B.1) 2A-B = ", ResB_1

ResB_2_a = A.dot(B)
ResB_2_b = B.dot(A)
print "\n B.2.a) The matrix product between A and B is : AB = ", ResB_2_a
print "\n B.2.b) The matrix product between B and A is : BA = ", ResB_2_b

ResB_3_a = np.transpose(A.dot(B))
ResB_3_b = np.transpose(B).dot(np.transpose(A))
print "\n B.3.a) The transposed of the matrix product between A and B is : ", ResB_3_a
print "\n B.3.a) The matrix product between the transposed of B and the transposed of A is : ", ResB_3_b

ResB_4_a = np.linalg.det(A)
ResB_4_b = np.linalg.det(C)
print "\n B.4.a) |A| = ", ResB_4_a
print "\n B.4.a) |C| = ", ResB_4_b

print "\n B.5) I think that there is a problem with this question since none of the matrix have rows vectors which form an orthogonal set. The other possibility is that I did not understand the question correctly. \n"

ResB_6_a = np.linalg.inv(A)
ResB_6_b = np.linalg.inv(B)
print "\n B.6.a) The inverse of the matrix A is : ", ResB_6_a
print "\n B.6.b) The inverse of the matrix B is : ", ResB_6_b


 B.1) 2A-B =  [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]

 B.2.a) The matrix product between A and B is : AB =  [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]

 B.2.b) The matrix product between B and A is : BA =  [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]

 B.3.a) The transposed of the matrix product between A and B is :  [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]

 B.3.a) The matrix product between the transposed of B and the transposed of A is :  [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]

 B.4.a) |A| =  54.999999999999964

 B.4.a) |C| =  0.0

 B.5) I think that there is a problem with this question since none of the matrix have rows vectors which form an orthogonal set. The other possibility is that I did not understand the question correctly. 


 B.6.a) The inverse of the matrix A is :  [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]

 B.6.b) The inverse of the matrix B is :  [[ 0.16666667  0.0952381   0.2142

## Exercise C

In [14]:
import numpy as np

# Variables

A = np.matrix('1 2; 3 2')
B = np.matrix('2, -2; -2, 5')

# Answers

ResC_1 = np.linalg.eig(A)
ResC_1_a = ResC_1[0]
ResC_1_b = ResC_1[1]
print "\n C.1.a) The eigenvalues of the matrix A are : ", ResC_1_a
print "\n C.1.b) The eigenvectors of the matrix A are : ", ResC_1_b

ResC_2 = np.linalg.inv(ResC_1[1]).dot(A).dot(ResC_1[1])
print "\n C.2) The product V^{-1}AV is equal to : ", ResC_2

ResC_3 = ResC_1[1][0].dot(np.transpose(ResC_1[1][1]))
print "\n C.3) The scalar product between the eigenvectors of the matrix A is equal to : ", ResC_3
print "Notice : I don't find the same result in my writting part. I think that it is due to the fact that the program python didn't choose the same eigenvector as me."

temp1 = np.linalg.eig(B)
ResC_4 = temp1[1][0].dot(np.transpose(temp1[1][1]))
print "\n C.4) The scalar product between the two eigenvectors of B is equal to : ", ResC_4

print "\n C.5) If the eigenvectors are orthogonal, it means that they are in direct sum and they constitute a direct basis.   There are also other properties on the vector product for this type of eigenvectors."




 C.1.a) The eigenvalues of the matrix A are :  [-1.  4.]

 C.1.b) The eigenvectors of the matrix A are :  [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]

 C.2) The product V^{-1}AV is equal to :  [[-1.00000000e+00 -7.16083316e-16]
 [ 2.57955803e-17  4.00000000e+00]]

 C.3) The scalar product between the eigenvectors of the matrix A is equal to :  [[-0.03846154]]
Notice : I don't find the same result in my writting part. I think that it is due to the fact that the program python didn't choose the same eigenvector as me.

 C.4) The scalar product between the two eigenvectors of B is equal to :  [[0.]]

 C.5) If the eigenvectors are orthogonal, it means that they are in direct sum and they constitute a direct basis.   There are also other properties on the vector product for this type of eigenvectors.
